import { Suspense } from "react";
import Header from "@/components/layouts/Header";
import { Shell } from "@/components/layouts/Shell";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { AddProductToCartForm } from "@/features/carts";
import { ProductCommentsSection } from "@/features/comments";
import {
  BuyNowButton,
  ProductCard,
  ProductImageShowcase,
} from "@/features/products";
import { AddToWishListButton } from "@/features/wishlists";
import { gql } from "@/gql";
import { getClient } from "@/lib/urql";
import { Metadata } from "next";
import { notFound } from "next/navigation";

type Props = {
  params: {
    slug: string;
  };
};
export const metadata: Metadata = {
  title: `THE FURNITURE STORE | Ecommerce Platforum Built with Nextjs 14.`,
  description: "Generated by create next app",
};

const ProductDetailPageQuery = gql(/* GraphQL */ `
  query ProductDetailPageQuery($productSlug: String) {
    productsCollection(filter: { slug: { eq: $productSlug } }) {
      edges {
        node {
          id
          name
          description
          rating
          price
          tags
          totalComments
          ...ProductImageShowcaseFragment
          commentsCollection(first: 5) {
            edges {
              node {
                ...ProductCommentsSectionFragment
              }
            }
          }
          collections {
            id
            label
            slug
          }
        }
      }
    }
    recommendations: productsCollection(first: 4) {
      edges {
        node {
          id
          ...ProductCardFragment
        }
      }
    }
  }
`);

async function ProductDetailPage({ params }: Props) {
  // Use direct fetch since URQL has issues with fragments
  const { env } = await import("@/env.mjs");
  const graphqlUrl = `https://${env.NEXT_PUBLIC_SUPABASE_PROJECT_REF}.supabase.co/graphql/v1`;

  // Include fragment definitions in the query
  const query = `
    fragment ProductImageShowcaseFragment on products {
      id
      featuredImage: medias {
        id
        key
        alt
      }
      images: product_mediasCollection(orderBy: [{ priority: DescNullsLast }]) {
        edges {
          node {
            media {
              id
              key
              alt
            }
          }
        }
      }
    }
    
    fragment ProductCardFragment on products {
      id
      name
      description
      rating
      slug
      badge
      price
      featuredImage: medias {
        id
        key
        alt
      }
      collections {
        id
        label
        slug
      }
    }
    
    fragment ProductCommentsSectionFragment on comments {
      id
      comment
      profile {
        name
      }
    }
    
    query ProductDetailPageQuery($productSlug: String) {
      productsCollection(filter: { slug: { eq: $productSlug } }) {
        edges {
          node {
            id
            name
            description
            rating
            price
            tags
            totalComments
            ...ProductImageShowcaseFragment
            commentsCollection(first: 5) {
              edges {
                node {
                  ...ProductCommentsSectionFragment
                }
              }
            }
            collections {
              id
              label
              slug
            }
          }
        }
      }
      recommendations: productsCollection(first: 4) {
        edges {
          node {
            id
            ...ProductCardFragment
          }
        }
      }
    }
  `;

  const response = await fetch(graphqlUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      apikey: env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    },
    body: JSON.stringify({
      query,
      variables: { productSlug: params.slug },
    }),
  });

  const json = await response.json();

  if (json.errors) {
    console.error("❌ GraphQL Errors:", json.errors);
    console.error("❌ Query variables:", { productSlug: params.slug });
    return notFound();
  }

  const data = json.data;

  console.log("📦 Product query result:", {
    hasData: !!data,
    hasProductsCollection: !!data?.productsCollection,
    edgesLength: data?.productsCollection?.edges?.length,
    slug: params.slug,
  });

  if (
    !data ||
    !data.productsCollection ||
    !data.productsCollection.edges ||
    data.productsCollection.edges.length === 0
  ) {
    console.error("❌ Product not found:", params.slug);
    console.error("❌ GraphQL Response:", JSON.stringify(data, null, 2));
    return notFound();
  }

  const { id, name, description, price, commentsCollection, totalComments } =
    data.productsCollection.edges[0].node;

  return (
    <Shell>
      <div className="grid grid-cols-12 gap-x-8">
        <div className="space-y-8 relative col-span-12 md:col-span-7">
          <ProductImageShowcase data={data.productsCollection.edges[0].node} />
        </div>

        <div className="col-span-12 md:col-span-5">
          <section className="flex justify-between items-start max-w-lg">
            <div>
              <h1 className="text-4xl font-semibold tracking-wide mb-3">
                {name}
              </h1>
              <p className="text-2xl font-semibold mb-3">{`$${price}`}</p>
            </div>
            <AddToWishListButton productId={id} />
          </section>

          <section className="flex mb-8 items-end space-x-5">
            <Suspense>
              <AddProductToCartForm productId={id} />
            </Suspense>

            <BuyNowButton productId={id} />
          </section>

          <section>
            <p>{description}</p>

            <Accordion type="single" collapsible>
              <AccordionItem value="product-details">
                <AccordionTrigger>Product Details</AccordionTrigger>
                <AccordionContent>
                  <div className="space-y-3">
                    <p>
                      This piece features a timeless design that seamlessly
                      blends functionality with modern aesthetics. Crafted with
                      attention to detail, it&apos;s built to last and designed
                      to enhance any living space.
                    </p>
                    <p>
                      The furniture is constructed from high-quality materials
                      and finished with a durable protective coating. Each piece
                      is carefully inspected to ensure it meets our quality
                      standards before shipping.
                    </p>
                    <p>
                      Perfect for modern homes, apartments, and office spaces.
                      The design complements a variety of interior styles from
                      contemporary to minimalist.
                    </p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="technical-information">
                <AccordionTrigger>Technical Information</AccordionTrigger>
                <AccordionContent>
                  <div className="space-y-3">
                    <div>
                      <strong>Dimensions:</strong> Please refer to product
                      specifications for exact measurements. Standard sizing
                      ensures compatibility with most room layouts.
                    </div>
                    <div>
                      <strong>Weight Capacity:</strong> Designed to support
                      standard household use. Maximum weight capacity varies by
                      model.
                    </div>
                    <div>
                      <strong>Assembly:</strong> Some assembly required. All
                      necessary hardware and detailed instructions included.
                      Estimated assembly time: 30-60 minutes.
                    </div>
                    <div>
                      <strong>Care Instructions:</strong> Clean with a soft,
                      damp cloth. Avoid harsh chemicals or abrasive cleaners.
                      For wood surfaces, use furniture polish as needed.
                    </div>
                    <div>
                      <strong>Warranty:</strong> One-year limited warranty
                      covering manufacturing defects. Warranty details provided
                      with purchase.
                    </div>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="shipping-returns">
                <AccordionTrigger>Shipping & Returns</AccordionTrigger>
                <AccordionContent>
                  Shipping & Returns Spend $80 to receive free shipping for a
                  limited time. Oversized items require additional handling
                  fees. Learn more Except for furniture, innerwear, and food,
                  merchandise can be returned or exchanged within 30 days of
                  delivery. Learn more
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </section>
        </div>
      </div>

      <Header heading={`We Think You'll Love`} />

      <div className="container grid grid-cols-2 lg:grid-cols-4 gap-x-8 ">
        {data.recommendations &&
          data.recommendations.edges.map(({ node }) => (
            <ProductCard key={node.id} product={node} />
          ))}
      </div>

      <ProductCommentsSection
        comments={
          commentsCollection
            ? commentsCollection.edges.map(({ node }) => node)
            : []
        }
        totalComments={totalComments}
      />
    </Shell>
  );
}

export default ProductDetailPage;
